-- Run this in Supabase SQL Editor for a fresh project database.
-- The FastAPI backend can also create these tables on startup, but this
-- script lets you prepare the schema directly in Supabase.

begin;

create table if not exists public.users (
    id integer generated by default as identity primary key,
    name varchar,
    role varchar,
    identifier varchar unique,
    hashed_password varchar,
    department varchar,
    year integer,
    semester integer,
    dob date,
    address text,
    blood_group varchar,
    phone_number varchar,
    parent_phone_number varchar,
    face_samples jsonb
);

create index if not exists ix_users_name on public.users (name);
create index if not exists ix_users_identifier on public.users (identifier);

create table if not exists public.embeddings (
    id integer generated by default as identity primary key,
    user_id integer references public.users(id) on delete cascade,
    embedding_vector jsonb
);

create index if not exists ix_embeddings_user_id on public.embeddings (user_id);

create table if not exists public.attendance (
    id integer generated by default as identity primary key,
    user_id integer references public.users(id) on delete cascade,
    date date,
    time time,
    session varchar,
    status varchar,
    constraint uq_attendance_user_date_session unique (user_id, date, session)
);

create index if not exists ix_attendance_user_id on public.attendance (user_id);
create index if not exists ix_attendance_date on public.attendance (date);

do $$
begin
    if not exists (
        select 1
        from pg_constraint
        where conname = 'uq_attendance_user_date_session'
    ) then
        alter table public.attendance
            add constraint uq_attendance_user_date_session unique (user_id, date, session);
    end if;
end $$;

create table if not exists public.staff_class_assignments (
    id integer generated by default as identity primary key,
    staff_user_id integer references public.users(id) on delete cascade,
    department varchar not null,
    year integer not null,
    semester integer not null,
    section varchar not null default 'all',
    assignment_type varchar not null
);

create index if not exists ix_staff_class_assignments_staff_user_id
    on public.staff_class_assignments (staff_user_id);

create table if not exists public.settings (
    id integer generated by default as identity primary key,
    holidays jsonb default '[]'::jsonb,
    morning_time_start time,
    morning_time_end time,
    afternoon_time_start time,
    afternoon_time_end time,
    staff_morning_time_start time,
    staff_morning_time_end time,
    staff_evening_time_start time,
    staff_evening_time_end time
);

insert into public.settings (
    holidays,
    morning_time_start,
    morning_time_end,
    afternoon_time_start,
    afternoon_time_end,
    staff_morning_time_start,
    staff_morning_time_end,
    staff_evening_time_start,
    staff_evening_time_end
)
select
    '[]'::jsonb,
    time '08:30',
    time '12:30',
    time '13:30',
    time '16:30',
    time '08:30',
    time '12:30',
    time '13:30',
    time '16:30'
where not exists (select 1 from public.settings);

create table if not exists public.calendar_rules (
    id integer generated by default as identity primary key,
    start_date date not null,
    end_date date not null,
    audience varchar not null,
    day_type varchar not null,
    reason varchar,
    constraint ck_calendar_rules_date_order check (end_date >= start_date)
);

create index if not exists ix_calendar_rules_start_date on public.calendar_rules (start_date);
create index if not exists ix_calendar_rules_end_date on public.calendar_rules (end_date);

create table if not exists public.alembic_version (
    version_num varchar(32) primary key
);

insert into public.alembic_version (version_num)
values ('0001_initial_schema')
on conflict (version_num) do nothing;

commit;
